# Generated by Django 5.0.3 on 2024-04-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passernger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passernger',
            new_name='Passenger',
        ),
    ]
