# Generated by Django 5.0.3 on 2024-04-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_passernger_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='second',
            new_name='last',
        ),
    ]
